### ISSUE TITLE
[kitty] Htop and autosuggestions not visible on dark theme

### ISSUE THREAD

**Issue by prateekmedia** [nautilor/mountain-peek#2]
![image](https://user-images.githubusercontent.com/41370460/151236778-7b4ab664-0200-4cd3-9449-5c53eeb98891.png)

**Comment by nautilor** [comment]
try changing the colors in htop config

https://github.com/hishamhm/htop/issues/35

**Comment by nautilor** [comment]
Just press **shift+c** and set the Colors to Broken Gray

![image](https://user-images.githubusercontent.com/9730983/151249515-07a7fff1-8f7e-4e04-b7f0-0b199a12c993.png)

**Comment by nautilor** [comment]
in the meantime I will find a better color instead of the one used at the moment

**Comment by nautilor** [comment]
I have updated the colorscheme changing the **color0** and **color8** to a lighter version of the previous one

I also included some Dark shades variant that you can use as an alternative to the one currently configured


You can find them in the README or down here


## Dark Shades
| **Color** | **Hex value** | **Colors Name** | **Preview** |
| ----- | --------- | ------------ | ------- |
| Black 1 | #101216 | Woodsmoke | ![Woodsmoke](https://via.placeholder.com/24/101216/000000?text=+) |
| Black 2 | #1B1E25 | Shark | ![Shark](https://via.placeholder.com/24/1B1E25/000000?text=+) |
| Black 3 | #232730 | Charade | ![Charade](https://via.placeholder.com/24/232730/000000?text=+) |
| Black 4 | #313743 | Bright Gray  | ![Bright Gray](https://via.placeholder.com/24/313743/000000?text=+) |
| Black 5 | #4b5365 | River Bed | ![River Bed](https://via.placeholder.com/24/4b5365/000000?text=+) |

**Comment by prateekmedia** [comment]
Ok I will try it.
