### ISSUE TITLE
Possibility of darker for dark variant and lighter for light variant?

### ISSUE THREAD

**Issue by prmadev** [nautilor/mountain-peek#3]
Hello! My compliments to the chief! Your colorscheme is wonderful!
I have been ricing with it and there are some situations which an added shade would help a lot in keeping consistency. 
More specifically I mean for colors, an added variant would help. 
![drawing](https://user-images.githubusercontent.com/28535608/151494302-6b5efa75-573d-4892-8cc7-c4a7f357a1ca.svg)
Consider when ricing a websites or application which have cursor-aware buttons. in those cases different shades of color could be useful. for dark variant, a lighter scheme can already be drawn from the light variant. And vice-versa. As i understand the difference is about 15% value change. So logically the reverse can also be done. 

Though I understand explicitely adding values to the pallet can be double-edge-sword. On the one hand, more colors can add confusion in "which one should one use?". On the other hand explicitally specifying this added shade can help ricers and developers in line and prevent unstandard values in the wild, when the need for the missing values arises. 

Thanks again for your much appreciated taste!

**Comment by nautilor** [comment]
Based on your suggestion I pulled out some colors but decided to increment/decrement by 10 as some colors were getting too light for my taste, I updated the README with them but I still want to refine them a little and then do the same with the light one

| **Color** | **Hex value** | **Colors Name** | **Preview** |
| ----- | --------- | ------------ | ------- |
| Dark Red | #742f37 | --- | ![---](https://via.placeholder.com/24/742f37/000000?text=+) |
| Red | #973D46 | --- | ![Shark](https://via.placeholder.com/24/973D46/000000?text=+) |
| Light Red | #b8515b | --- | ![---](https://via.placeholder.com/24/b8515b/000000?text=+) |
| Dark Green | #638349 | --- | ![---](https://via.placeholder.com/24/638349/000000?text=+) |
| Green | #7ca25c | --- | ![Shark](https://via.placeholder.com/24/7ca25c/000000?text=+) |
| Light Green | #96b67c | --- | ![---](https://via.placeholder.com/24/96b67c/000000?text=+) |
| Dark Yellow | #d19723 | --- | ![---](https://via.placeholder.com/24/d19723/000000?text=+) |
| Yellow | #e0ae4a | --- | ![Shark](https://via.placeholder.com/24/e0ae4a/000000?text=+) |
| Light Yellow | #e7c073 | --- | ![---](https://via.placeholder.com/24/e7c073/000000?text=+) |
| Dark Blue | #406182 | --- | ![---](https://via.placeholder.com/24/406182/000000?text=+) |
| Blue | #517ba5 | --- | ![Shark](https://via.placeholder.com/24/517ba5/000000?text=+) |
| Light Blue | #6f94b8 | --- | ![---](https://via.placeholder.com/24/6f94b8/000000?text=+) |
| Dark Magenta | #744e6d | --- | ![---](https://via.placeholder.com/24/744e6d/000000?text=+) |
| Magenta | #94628a	 | --- | ![---](https://via.placeholder.com/24/94628a/000000?text=+) |
| Light Magenta | #a97ea1 | --- | ![---](https://via.placeholder.com/24/a97ea1/000000?text=+) |
| Dark Cyan | #4d807f | --- | ![---](https://via.placeholder.com/24/4d807f/000000?text=+) |
| Cyan | #5f9f9e	 | --- | ![---](https://via.placeholder.com/24/5f9f9e/000000?text=+) |
| Light Cyan | #80b3b2 | --- | ![---](https://via.placeholder.com/24/80b3b2/000000?text=+) |

**Comment by prmadev** [comment]
Thank you very much. I will use these values, but keep track of the further refinements!
