### ISSUE TITLE
The matter of naming

### ISSUE THREAD

**Issue by prmadev** [nautilor/mountain-peek#4]
Hello again! 
I'm currently working on the neovim color theme (as discussed before in r/unixporn reddit). However, there seems to be another colorscheme called mountain as you are aware.
Considering that fact, to avoid confusion I would like to add something to the dark and light variant, in order distinguish them from the-other-mountain. 
For now, I just called the dark variant, darkmountain, which is... not creative :D. 
I would appreciate it if you can name dark and light variant so that I shall move on with that. 
One case that I particularly loved was the darkfox theme, which named their variants _DayFox_, _DawnFox_, _DuskFox_, _NightFox_ and _NordFox_. It has nothing to do with this theme, I just like to throw useless trivia that I enjoy, any chance I get. :grin:

**Comment by nautilor** [comment]
I am aware of this, and I was thinking of renaming this to something like `Mountain Peek` to not confuse it with the other one.

The naming could simply be `Mountain Peek Dark` and `Mountain Peek Light` or `Night` and `Snow` variant as the main BG color for the dark is almost full black and the one for the light theme is almost full white.

**Comment by prmadev** [comment]
I think that would work perfectly. Thank for your considerations.
